name: rakna_graduation_project
description: "A new Flutter project."


version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


 
  cupertino_icons: ^1.0.2
  provider: ^6.1.1
  curved_navigation_bar: ^1.0.3
  hidden_drawer_menu: ^3.0.1
  gap: ^3.0.1
  google_fonts: ^6.1.0
  firebase_auth: ^4.17.8
  firebase_core: ^2.27.1
  animate_do: ^3.3.4
  flutter_easyloading: ^3.0.5
  lottie: ^3.1.0
  bot_toast: ^4.1.3
  google_sign_in: ^6.2.1
  awesome_dialog: ^3.2.0
  image_picker: ^1.0.7
  logger: ^2.1.0
  flutter_rating_bar: ^4.0.1
  qr_flutter: ^4.1.0
  barcode_scan2: ^4.3.0
  flutter_ticket: ^1.0.1
  ticket_widget: ^1.0.2
  table_calendar: ^3.1.0
  flutter_colorpicker: ^1.0.3
  cloud_firestore: ^4.15.10
  firebase_storage: ^11.6.11
  
  




dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/icons/
    - assets/icons_1/
    - assets/images/

  
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
